export const API_ENDPOINTS = {
  LOGIN: '/signin',
  REGISTER: '/register',
  CAREER: '/career',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/category',
  UPDATEUSER:'/updateuser',
  PROJECTFILES:'/files',
  CATEGORIES_HOME3: '/category',
  FOLDER:'/folder',
  CART: '/cart',
  PROJECTFOLDER:'/projectfolder',
  CHANGEPASSWORD:'/changepassword',
  CLEARCART:'/clearcart',
  DELETEITEM:"/deleteitem",
  DIETARY: '/dietary',
  WISHLIST:'/wishlist',
  CONTACTUS:'/contactus',
  BRANDS: '/brands',
  PROJECT:'/project',
  PROJECTS:'/projects',
  PRODUCTS: '/template',
  PRODUCT: '/template',
  RELATED_PRODUCTS: '/template',
  BEST_SELLER_GROCERY_PRODUCTS: '/template',
  FLASH_SELL_PRODUCTS: '/template',
  BEST_SELLER_PRODUCTS: '/template',
  NEW_ARRIVAL_PRODUCTS: '/template',
  POPULAR_PRODUCTS: '/template',
  COOKIES_PRODUCTS: '/template',
  CHIPS_PRODUCTS: '/template',
  POPCORN_JERKY_PRODUCTS: '/template',
  ELETRONIC_PRODUCTS: '/template',
  FASHION_PRODUCTS: '/template',
  ELECTRONIC_CATEGORY: '/category',
  PHONES_CATEGORY: '/category',
  COMPUTER_CATEGORY: '/category',
  CLOTH_CATEGORY: '/category',
  SEARCH: '/template',
  ORDERS: '/order',
  ORDER: '/order',
  ORDER_STATUS: '/order-status',
  ADDRESS: '/address',
  PAYMENT: '/payment',
  CONTACT: '/contact.json',
  SHOP: '/shop',
  SHOPS: '/shops',
  BLOGS: '/blog',
  BLOGDETAILS: '/blog',
  FAQ: '/faq',
  TESTIMONIALS: '/testimonial',
  STRIPE: '/stripe'
};
